CONTRACT_ADDRESS = 'DEPLOYED CONTRACT ADDRESS'
WALLET_PRIVATE_KEY = 'TESTNET WALLET PK'
WALLET_ADDRESS = 'TESTNET WALLET ADDRESS'

INFURA_URL = 'INFURA API URL'

DB_STRING = 'postgresql://user:password@localhost:5432/dating-app'

PINATA_KEY = 'PINATA API KEY'
PINATA_SECRET = 'PINATA API SECRET'
